### ISSUE TITLE
Mqtt user e password

### ISSUE THREAD

**Issue by wifi75** [sirkus7/ospiLCD-mqtt#4]
Hello How I can set user end password line in configuration file?

**Comment by kristoficko** [comment]
In the script file, before client.connect, specify your user and password:
client.username_pw_set("user", "password")

**Comment by wifi75** [comment]
> In the script file, before client.connect, specify your user and password: client.username_pw_set("user", "password")

Hello I looked at ospiLCD-mqtt.py file but there is no client.connect entry

**Comment by kristoficko** [comment]
Look at the script here on GitHub: [line 257](https://github.com/sirkus7/ospiLCD-mqtt/blob/5b49e6231511e70617166fa3629119d87ad4cb71/ospiLCD-mqtt.py#L257)

**Comment by wifi75** [comment]
> Look at the script here on GitHub: [line 257](https://github.com/sirkus7/ospiLCD-mqtt/blob/5b49e6231511e70617166fa3629119d87ad4cb71/ospiLCD-mqtt.py#L257)

like this ?

# === Setup MQTT client, actions ===
client = mqtt.Client()  
client.on_connect = mqtt_connect  
client.on_message = mqtt_message  
client.connect(mqttAddress, mqttPort, 60)
**client.username_pw_set("user", "password")**
client.loop_forever()



and then  ??

# Set MQTT info (defaults to localhost, if MQTT server is running on Pi)
mqttAddress = "127.0.0.1"
mqttPort   = "1883"
user = "myuser"
password = "password"

**Comment by kristoficko** [comment]
As I wrote initially,  I believe the user and password need to be specified
BEFORE the client.connect function is called.

**Comment by wifi75** [comment]
ok  like this:

```
# === Setup MQTT client, actions ===
client = mqtt.Client()  
client.on_connect = mqtt_connect  
client.on_message = mqtt_message  
client.username_pw_set("user", "password")
client.connect(mqttAddress, mqttPort, 60)
client.loop_forever()
```


but also this is ocrrect?
```
mqttAddress = "127.0.0.1"
mqttPort = "1883"
user = "myuser"
password = "password"
```

I tried like this but after running the scrip it gives me an error:

```
root@opensprinkler:/home/pi# ./ospiLCD-mqtt.py
Traceback (most recent call last):
  File "./ospiLCD-mqtt.py", line 231, in <module>
    dotsize=8, charmap='A02', auto_linebreaks=True, backlight_enabled=True)
  File "/usr/local/lib/python2.7/dist-packages/RPLCD/i2c.py", line 168, in __init__
    auto_linebreaks=auto_linebreaks)
  File "/usr/local/lib/python2.7/dist-packages/RPLCD/lcd.py", line 98, in __init__
    self._init_connection()
  File "/usr/local/lib/python2.7/dist-packages/RPLCD/i2c.py", line 173, in _init_connection
    self.bus = SMBus(self._port)
IOError: [Errno 2] No such file or directory
```
